// Behavioral DOM harness, not a Safari layout renderer.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {defaults} from '../engine.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
class Element{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.options=this.children;this.style={};this.dataset={};this.value='';this.textContent='';this.hidden=false;this.disabled=false;this.checked=false;this.open=false;this.type='';this.attributes={};this.className='';const classes=new Set();this.classList={toggle:(k,on)=>on?classes.add(k):classes.delete(k),contains:k=>classes.has(k)};}
 getContext(){return null;}append(...els){this.children.push(...els);}add(e){this.append(e);}replaceChildren(...els){this.children.splice(0,this.children.length,...els);}setAttribute(k,v){this.attributes[k]=v;}showModal(){this.open=true;}close(){this.open=false;}click(){if(!this.disabled)return this.onclick?.({target:this});}matches(q){return q.split(',').includes(this.tagName);}querySelectorAll(q){const all=this.children.flatMap(c=>[c,...c.querySelectorAll('*')]);if(q==='*')return all;if(q==='[data-key]')return all.filter(e=>e.dataset.key);const m=q.match(/^\[data-key="([^"]+)"\]$/);if(m)return all.filter(e=>e.dataset.key===m[1]);return all.filter(e=>e.tagName===q);}querySelector(q){return this.querySelectorAll(q)[0]||null;}
}
function harness(configure=true){const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8'),els=new Map([...html.matchAll(/<(\w+)[^>]*\bid="([^"]+)"[^>]*>/g)].map(m=>{const e=new Element(m[1]);e.command=m[0].includes('data-command');return [m[2],e];}));
 const config=defaults();if(configure)config.tubes.forEach((t,i)=>t.ip='192.168.1.'+(100+i));
 const effects=['Solid','Breathe','Strobe','Juggles',...Array.from({length:30},(_,i)=>'Effect '+i)],devices=configure?Object.fromEntries(config.tubes.map(t=>[t.id,{id:t.id,ip:t.ip,ok:true,name:t.name,effects,palettes:['Default','Ocean','* Color 1'],audio:{enabled:true},fxdata:effects.map(()=> '!,!,Extra,,,Option;!,!,!;!'),state:{on:true,bri:128,transition:7,mainseg:0,seg:[{id:0,start:0,stop:100,fx:t.id<3?0:1,pal:0,col:[[255,0,0],[0,255,0],[0,0,255]],sx:90,ix:100,rev:false,mi:false}]}}])):{};
 const model={config,devices,scenes:[],token:'test',version:'3.0.0',pid:10},calls=[],timers=new Set();
 const document={getElementById:id=>els.get(id),createElement:t=>new Element(t),hidden:false,activeElement:null,querySelector:q=>q==='dialog[open]'?[...els.values()].find(e=>e.tagName==='dialog'&&e.open)||null:null,querySelectorAll:q=>q==='[data-command]'?[...els.values()].filter(e=>e.command):[]};
 const response=j=>({ok:true,json:async()=>structuredClone(j)});
 const context={document,localStorage:{getItem:()=>null,setItem(){}},location:{reload(){}},confirm:()=>true,Option:class extends Element{constructor(label,value){super('option');this.textContent=label;this.value=value;}},fetch:async(url,options)=>{if(!options)return response(model);const b=JSON.parse(options.body);calls.push({url,b});if(url==='/api/control'){for(const id of b.ids){const s=devices[id].state;for(const [k,v]of Object.entries(b.patch)){if(['on','bri','transition'].includes(k))s[k]=v;else if(k==='fx'){if(v==='Sound Brightness'){s.seg[0].fx=effects.indexOf('Juggles');devices[id].soundBrightness={active:true,floor:8};}else{s.seg[0].fx=effects.indexOf(v);devices[id].soundBrightness={active:false,floor:8};}}else if(k==='floor')devices[id].soundBrightness.floor=v;else if(k==='color')s.seg[0].col[v.slot]=v.rgb;}}return response({...model,results:b.ids.map(id=>({id,ok:true}))});}if(url==='/api/blackout'){for(const d of Object.values(devices))d.state.on=false;return response(model);}if(url==='/api/config')Object.assign(config,b);if(url==='/api/networks')return response({networks:['192.168.1']});if(url==='/api/scene/save')model.scenes.push({id:'scene1',name:b.name,ids:b.ids});if(url==='/api/update/status')return response({version:'3.0.0',source:'https://example.com/update.json',canRollback:true});return response(model);},setTimeout,clearTimeout,setInterval:(f,ms)=>{const id=setInterval(f,ms);timers.add(id);return id;},clearInterval:id=>{clearInterval(id);timers.delete(id);},console,Date,JSON,Math};
 vm.runInNewContext(fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),context);return {els,model,calls,close:()=>{for(const t of timers)clearInterval(t);}};
}
test('empty setup boots without changing hardware and opens five editable connection slots',async t=>{const h=harness(false);t.after(h.close);await delay(30);assert.equal(h.els.get('barCards').children.length,5);assert.match(h.els.get('noticeText').textContent,/Welcome/);assert.equal(h.els.get('powerOn').disabled,true);assert.equal(h.calls.length,0);await h.els.get('setupBtn').click();assert.equal(h.els.get('setup').open,true);assert.equal(h.els.get('tubeInputs').children.length,5);});
test('dashboard selects groups, paginates native effects and sends only explicitly changed controls',async t=>{const h=harness();t.after(h.close);const e=id=>h.els.get(id);await delay(30);assert.equal(e('barCards').children.length,5);assert.equal(e('effectGrid').children.length,9);assert.equal(e('selectedCount').textContent,'5 selected');assert.match(e('stateSummary').textContent,/Different effects/);assert.equal(h.calls.filter(x=>x.url==='/api/control').length,0);
 e('selectA').click();assert.equal(e('speedControl').hidden,true);assert.equal(e('colorSlots').children.length,4);assert.equal(e('colorSlots').children[3].disabled,true);await e('powerOff').click();assert.deepEqual(h.calls.at(-1).b,{ids:[0,1,2],patch:{on:false}});assert.equal(h.model.devices[3].state.on,true);
 e('brightness').value='40';e('brightness').oninput();await e('brightness').onchange();assert.deepEqual(h.calls.at(-1).b.patch,{bri:102});assert.equal(h.model.devices[0].state.seg[0].col[0][0],255);
 e('nextPage').click();assert.equal(e('pageLabel').textContent,'2 / 4');e('search').value='Breathe';e('search').oninput();assert.equal(e('effectGrid').children.length,1);await e('effectGrid').children[0].click();assert.deepEqual(h.calls.at(-1).b.patch,{fx:'Breathe'});assert.equal(e('speedControl').hidden,false);assert.equal(e('intensityControl').hidden,false);assert.equal(e('speedLabel').textContent,'Speed');
 e('selectB').click();e('colorSlots').children[1].click();e('exactColor').click();e('hex').value='#123456';e('hex').onchange();await e('applyColor').click();assert.deepEqual(h.calls.at(-1).b,{ids:[3,4],patch:{color:{slot:1,rgb:[18,52,86]}}});assert.deepEqual(h.model.devices[0].state.seg[0].col[1],[0,255,0]);
 e('saveScene').click();e('sceneName').value='Back blue';await e('confirmScene').click();assert.deepEqual(h.model.scenes[0].ids,[3,4]);assert.equal(e('scenes').children.length,1);await e('barCards').children[4].children[3].onchange();assert.equal(h.model.config.tubes[4].group,2);e('selectC').click();assert.equal(e('selectedCount').textContent,'1 selected');e('beatQuick').click();assert.equal(e('beatHelp').open,true);e('beatHelp').close();await e('soundQuick').click();assert.equal(e('floorControl').hidden,false);assert.match(e('stateSummary').textContent,/Sound Brightness/);e('floor').value='15';await e('floor').onchange();assert.equal(h.model.devices[4].soundBrightness.floor,15);assert.deepEqual(h.calls.at(-1).b,{ids:[4],patch:{floor:15}});
 await e('settingsBtn').click();assert.equal(e('settings').open,true);assert.equal(e('rollback').hidden,false);await e('blackout').click();assert.ok(Object.values(h.model.devices).every(d=>d.state.on===false));
});
