// Browser API harness; this verifies UI behavior, not a Safari rendering engine.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {defaults,effects} from '../engine.mjs';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
class Element{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.options=this.children;this.style={};this.dataset={};this.value='';this.textContent='';this.hidden=false;this.disabled=false;this.checked=false;this.open=false;this.events={};const classes=new Set();this.classList={toggle:(k,b)=>b?classes.add(k):classes.delete(k),contains:k=>classes.has(k)};}
 append(...els){this.children.push(...els);}add(el){this.append(el);}replaceChildren(...els){this.children.splice(0,this.children.length,...els);}setAttribute(){}addEventListener(k,fn){this.events[k]=fn;}showModal(){this.open=true;}close(){this.open=false;}focus(){}click(){if(!this.disabled)return this.onclick?.({target:this});}getBoundingClientRect(){return {width:650,height:450,left:0,top:0};}getContext(){return new Proxy({createImageData:(w,h)=>({data:new Uint8ClampedArray(w*h*4)})},{get:(obj,k)=>obj[k]||(()=>{})});}querySelectorAll(){return this.children.flatMap(c=>[...(c.dataset.key?[c]:[]),...c.querySelectorAll()]);}
}
test('dashboard boots; independent group RGB edits, onboard mic selection, layout, live samples, and no browser audio',{timeout:6000},async t=>{
 const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8'),els=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));
 for(let i=0;i<2;i++){const b=new Element('button');b.dataset.group=i;els.get('groupTabs').append(b);}
 const tests=['red','green','blue','white'].map(color=>{const e=new Element('button');e.dataset.test=color;return e;});
 let config=defaults(),status={live:false,busy:false,devices:{},preview:{},previewErrors:{},micReady:false};const calls=[],timers=new Set(),events={};
 const response=j=>({ok:true,json:async()=>structuredClone(j)});
 const document={getElementById:id=>els.get(id),createElement:tag=>new Element(tag),addEventListener:(k,f)=>events[k]=f,querySelectorAll:q=>q==='[data-test]'?tests:q==='dialog'?[els.get('setup'),els.get('updates')]:[],hidden:false};
 const ctx={document,window:{devicePixelRatio:1,addEventListener(){}},crypto:{randomUUID:()=> 'test-ui'},navigator:{mediaDevices:{getUserMedia:()=>{throw Error('Mac microphone must not be used');}}},fetch:async(url,options)=>{if(url==='/api/state')return response({config,status,effects,networks:[],token:'token'});const body=JSON.parse(options.body);calls.push({url,body});if(url==='/api/config')Object.assign(config,body);if(url==='/api/microphone')status.micReady=true;if(url==='/api/start')status.live=true;if(url==='/api/stop'||url==='/api/blackout')status.live=false;return response({config,status,ok:true,message:'Connected'});},Option:class extends Element{constructor(label,value){super('option');this.textContent=label;this.value=value;}},performance,setTimeout,clearTimeout,setInterval:(f,ms)=>{const id=setInterval(f,ms);timers.add(id);return id;},clearInterval:id=>{timers.delete(id);clearInterval(id);},Uint8Array,Uint8ClampedArray,Math,Date,JSON,console,Blob,URL};
 t.after(()=>{for(const timer of timers)clearInterval(timer);});vm.runInNewContext(fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),ctx);await delay(40);
 assert.equal(els.get('effects').children.length,12);assert.equal(els.get('selectedTube').options.length,5);assert.equal(els.get('noticeText').textContent,'');
 els.get('colors').children[0].click();els.get('red').value=255;els.get('green').value=0;els.get('blue').value=0;els.get('red').oninput();els.get('doneColor').click();els.get('brightness').value='47';els.get('brightness').oninput();await els.get('apply').click();assert.equal(config.groups[0].colors[0],'#ff0000');assert.equal(config.groups[0].brightness,.47);assert.equal(config.groups[1].brightness,.3);
 els.get('groupTabs').children[1].click();els.get('effects').children.find(b=>b.dataset.effect==='loop').click();els.get('addColor').click();els.get('hex').value='#123456';els.get('hex').onchange();els.get('doneColor').click();await els.get('apply').click();assert.equal(config.groups[1].effect,'loop');assert.equal(config.groups[1].colors.at(-1),'#123456');assert.equal(config.groups[0].effect,'fixed');
 els.get('editMode').click();els.get('rotation').oninput({target:{value:'45'}});await els.get('saveLayout').click();assert.equal(config.tubes[0].angle,45);
 els.get('microphone').value='3';await els.get('microphone').onchange();await els.get('connectMic').click();assert.equal(config.microphone,3);assert.equal(status.micReady,true);assert.ok(calls.some(c=>c.url==='/api/microphone'));assert.ok(!calls.some(c=>c.url==='/api/audio'));
 await els.get('goLive').click();assert.equal(status.live,true);assert.equal(els.get('microphone').disabled,true);await els.get('blackout').click();assert.equal(status.live,false);
 const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');assert.ok(!/getUserMedia|AudioContext|\/api\/disconnect|visibilitychange/.test(source));
});
