import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import dgram from 'node:dgram';import {spawn} from 'node:child_process';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
test('five native controllers: group isolation, preflight, partial failures, all-off, scenes and persistence',{timeout:25000},async t=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'tube-v3-'));let child,offline='',rejectWrite='',writes=[],udpFrames=0;
 const ds=Object.fromEntries([1,2,3,4,5].map(i=>['127.0.0.'+i,{effects:i%2?['Solid','Breathe','Strobe']:['Breathe','Strobe','Solid'],palettes:i%2?['Default','Ocean']:['Ocean','Default'],state:{on:true,bri:90+i,transition:0,udpn:{send:true,rgrp:1},mainseg:0,seg:[{id:0,start:0,stop:50,fx:0,pal:0,col:[[255,80,0,33],[0,0,255,0],[0,0,0,0]],sx:120,ix:140},{id:1,start:50,stop:100,fx:1,pal:1,col:[[0,255,0,0],[5,6,7,0],[0,0,0,0]],sx:80,ix:90,rev:true}]}}]));
 const mock=http.createServer(async(req,res)=>{const ip=req.headers['x-tuberoom-test-ip'],d=ds[ip];res.setHeader('Content-Type','application/json');if(!d||ip===offline){res.writeHead(503);res.end('{}');return;}let b;if(req.method==='POST'){let raw='';for await(const chunk of req)raw+=chunk;b=JSON.parse(raw);writes.push({ip,route:req.url,b});if(ip===rejectWrite){res.writeHead(500);res.end('{}');return;}const {seg,...rest}=b;Object.assign(d.state,rest);if(seg)for(const u of seg){const s=d.state.seg.find(s=>s.id===u.id),{col,...rest}=u;Object.assign(s,rest);if(col)s.col=col.map((c,i)=>Array.isArray(c)?c:[c.r??s.col[i][0],c.g??s.col[i][1],c.b??s.col[i][2],c.w??s.col[i][3]??0]);}res.end('{"success":true}');return;}
 if(req.url==='/json/fxdata'){res.end(JSON.stringify(d.effects.map(()=> 'Speed,Intensity,Custom 1,Custom 2,Custom 3,Option 1;!;!')));return;}if(req.url==='/json/live'){res.end('{"leds":["ff0000","0000ff"]}');return;}res.end(JSON.stringify(req.url==='/json/state'?d.state:{state:d.state,info:{ver:'0.15.1',leds:{count:100}},effects:d.effects,palettes:d.palettes}));});
 await new Promise(r=>mock.listen(0,'127.0.0.1',r));const udp=dgram.createSocket('udp4');await new Promise(r=>udp.bind(4048,'127.0.0.1',r));udp.on('message',()=>udpFrames++);
 const old={version:2,groups:[{name:'Front'},{name:'Back'}],tubes:[0,1,2,3,4].map(id=>({id,ip:'127.0.0.'+(id+1),name:'Bar '+(id+1),enabled:true,group:id<3?0:1,x:200+id*100}))};fs.writeFileSync(path.join(data,'settings.json'),JSON.stringify(old));
 const launch=()=>{child=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,TUBEROOM_DATA:data,TUBEROOM_PORT:'18788',TUBEROOM_TEST:'1',TUBEROOM_WLED_PORT:String(mock.address().port)},stdio:'pipe'});child.stdout.resume();child.stderr.resume();};
 const close=async()=>{if(child?.exitCode===null){child.kill();await new Promise(r=>child.once('exit',r));}};t.after(async()=>{await close();udp.close();mock.close();fs.rmSync(data,{recursive:true,force:true});});
 let state;async function ready(){for(let i=0;i<80;i++){try{state=await(await fetch('http://127.0.0.1:18788/api/state')).json();return state;}catch{await delay(30);}}throw Error('Server did not start');}
 const post=async(route,b={},headers={})=>{const r=await fetch('http://127.0.0.1:18788/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-TubeRoom-Token':state.token,...headers},body:JSON.stringify(b)});return {code:r.status,...await r.json()};};launch();await ready();assert.equal(state.config.tubes[0].ip,'127.0.0.1');assert.equal(state.config.groups[0].name,'Front');assert.equal(writes.length,0,'opening v3 does not change hardware');
 assert.equal((await post('control',{ids:[0],patch:{on:false}},{Origin:'https://evil.example'})).code,403);assert.equal((await post('config',{}, {'X-TubeRoom-Token':'bad'})).code,400);assert.equal((await post('refresh')).code,200);
 let r=await post('control',{ids:[0,1,2],patch:{fx:'Solid',pal:'Ocean'}});assert.equal(r.code,200);assert.equal(r.busy,false);assert.equal(ds['127.0.0.1'].state.seg[0].fx,0);assert.equal(ds['127.0.0.2'].state.seg[0].fx,2);assert.equal(ds['127.0.0.4'].state.udpn.send,true,'unselected bar is untouched');assert.ok(writes.every(w=>w.b.seg.every(s=>!('stop'in s))));
 r=await post('control',{ids:[3,4],patch:{color:{slot:1,rgb:[12,34,56]}}});assert.equal(r.code,200);assert.deepEqual(ds['127.0.0.4'].state.seg[0].col[0],[255,80,0,33]);assert.deepEqual(ds['127.0.0.4'].state.seg[0].col[1],[12,34,56,0]);assert.deepEqual(ds['127.0.0.1'].state.seg[0].col[1],[0,0,255,0]);
 const before=writes.length;offline='127.0.0.2';r=await post('control',{ids:[0,1,2],patch:{bri:20}});assert.equal(r.code,400);assert.match(r.error,/Nothing changed/);assert.equal(writes.length,before);offline='';r=await post('control',{ids:[0,1],patch:{fx:'Made up'}});assert.equal(r.code,400);assert.equal(writes.length,before);
 rejectWrite='127.0.0.2';r=await post('control',{ids:[0,1,2],patch:{bri:44}});assert.equal(r.code,200);assert.deepEqual(r.results.map(x=>x.ok),[true,false,true]);rejectWrite='';
 r=await post('scene/save',{ids:[0,3],name:'Two looks'});assert.equal(r.code,200);const scene=r.scenes[0].id;const captured=structuredClone([ds['127.0.0.1'].state,ds['127.0.0.4'].state]);await post('control',{ids:[0,3],patch:{bri:200,fx:'Breathe'}});r=await post('scene/apply',{id:scene});assert.equal(r.code,200);assert.deepEqual(ds['127.0.0.4'].state.seg[0].col,captured[1].seg[0].col);assert.equal(ds['127.0.0.1'].state.bri,captured[0].bri);
 assert.equal((await post('preview')).previews.length,5);const quiet=writes.length;await delay(400);assert.equal(writes.length,quiet);assert.equal(udpFrames,0,'no pixel streaming or Mac audio relay');
 offline='127.0.0.3';r=await post('blackout');assert.equal(r.results.filter(x=>x.ok).length,4);assert.equal(ds['127.0.0.5'].state.on,false);offline='';
 await close();launch();await ready();assert.equal(state.scenes[0].name,'Two looks');assert.equal(state.config.groups[1].name,'Back');assert.deepEqual(JSON.parse(fs.readFileSync(path.join(data,'settings.json'))),old,'legacy preferences remain untouched for rollback');assert.equal((await post('scene/delete',{id:scene})).scenes.length,0);
});
