import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {FORMAT,FILES,validateBundle,installBundle,pointer,setSource,newer,fetchUpdate} from '../updater.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function bundle(version='1.2.0',broken=false){return {format:FORMAT,version,notes:'Test update',files:FILES.map(name=>{let content=fs.readFileSync(path.join(root,name),'utf8');if(name==='package.json'){const p=JSON.parse(content);p.version=version;content=JSON.stringify(p);}if(broken&&name==='server.mjs')content="throw Error('Intentional failed-release test');";return {path:name,content,sha256:hash(content)};})};}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
test('updates reject corruption, traversal, partial files, downgrades and invalid source URLs',()=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'tube-update-'));try{const b=bundle();assert.equal(validateBundle(b).version,'1.2.0');const bad=structuredClone(b);bad.files[0].content+=' ';assert.throws(()=>validateBundle(bad),/integrity/);bad.files[0].path='../settings.json';assert.throws(()=>validateBundle(bad),/Unexpected/);assert.throws(()=>validateBundle({...b,files:b.files.slice(1)}),/incomplete/);assert.throws(()=>installBundle(data,b,'2.0.0'),/not newer/);assert.equal(pointer(data),null);assert.throws(()=>setSource(data,'http://example.com/file'),/HTTPS/);assert.throws(()=>setSource(data,'https://user:pass@example.com/file'),/credentials/);assert.equal(newer('1.10.0','1.2.0'),true);assert.equal(newer('1.2.0','1.2.0'),false);const syntax=structuredClone(b);syntax.files[1].content='this is { invalid';syntax.files[1].sha256=hash(syntax.files[1].content);assert.throws(()=>installBundle(data,syntax,'1.1.0'),/syntax/);assert.equal(pointer(data),null);}finally{fs.rmSync(data,{recursive:true,force:true});}
});
test('install, automatic restart, failed-start recovery and manual rollback preserve user settings',{timeout:20000},async t=>{
 const originalVersion=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version;const pieces=originalVersion.split('.').map(Number),newVersion=[pieces[0],pieces[1],pieces[2]+1].join('.'),badVersion=[pieces[0],pieces[1],pieces[2]+2].join('.');
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'tube-runner-'));const child=spawn(process.execPath,['runner.mjs'],{cwd:root,env:{...process.env,TUBEROOM_DATA:data,TUBEROOM_PORT:'18790'},stdio:'pipe'});let errors='';child.stderr.on('data',s=>errors+=s);child.stdout.resume();
 t.after(async()=>{child.kill('SIGTERM');if(child.exitCode===null)await new Promise(r=>child.once('exit',r));fs.rmSync(data,{recursive:true,force:true});});
 let state;async function ready(version){for(let i=0;i<120;i++){try{const res=await fetch('http://127.0.0.1:18790/api/state');const s=await res.json();if(s.version===version){state=s;return s;}}catch{}await delay(60);}throw Error('App did not start version '+version+': '+errors);}
 const post=async(route,b={})=>{const r=await fetch('http://127.0.0.1:18790/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-TubeRoom-Token':state.token,'X-TubeRoom-Client':'updater-test'},body:JSON.stringify(b)});return {code:r.status,...await r.json()};};
 await ready(originalVersion);await delay(350);assert.equal((await post('update/status')).managed,true);state.config.groups[0].brightness=.43;state.config.groups[0].colors[0]='#123456';await post('config',{groups:state.config.groups});
 await post('update/source',{url:'https://example.com/latest.tuberoom-update.json'});const firstPID=state.pid;
 assert.equal((await post('update/install',{bundle:bundle(newVersion)})).code,200);await ready(newVersion);await delay(350);assert.notEqual(state.pid,firstPID);assert.equal(state.config.groups[0].brightness,.43);assert.equal(state.config.groups[0].colors[0],'#123456');assert.equal((await post('update/status')).source,'https://example.com/latest.tuberoom-update.json');assert.equal(pointer(data).pending,false);
 assert.equal((await post('update/install',{bundle:bundle(badVersion,true)})).code,200);
 // Wait until the failed release has actually exited, then check restoration.
 await delay(900);await ready(newVersion);await delay(350);assert.match((await post('update/status')).notice,/could not start/);assert.equal(state.config.groups[0].brightness,.43);
 assert.equal((await post('update/rollback')).code,200);await ready(originalVersion);assert.equal(state.config.groups[0].colors[0],'#123456');assert.equal((await post('update/status')).canRollback,false);
});

test('online checks download a validated bundle without installing and leave state intact on network failure',async t=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'tube-feed-'));t.after(()=>fs.rmSync(data,{recursive:true,force:true}));setSource(data,'https://example.com/updates/latest.json');
 let fail=false;t.mock.method(globalThis,'fetch',async(url,options)=>{assert.equal(url,'https://example.com/updates/latest.json');assert.equal(options.redirect,'error');if(fail)throw Error('Network offline');return new Response(JSON.stringify(bundle()),{headers:{'content-type':'application/json'}});});
 const checked=await fetchUpdate(data,'1.1.0');assert.equal(checked.available,true);assert.equal(checked.version,'1.2.0');assert.equal(pointer(data),null);assert.equal((await fetchUpdate(data,'1.2.0')).available,false);fail=true;await assert.rejects(()=>fetchUpdate(data,'1.1.0'),/offline/);assert.equal(pointer(data),null);
});
